### ISSUE TITLE
Linux Error when running latest release

### ISSUE THREAD

**Issue by scramble45** [sonik-br/GDMENUCardManager#44]
When running the latest release on my arch mainline rig I ran into the following error:
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.StringComparer.get_OrdinalIgnoreCase()
   at Avalonia.Media.KnownColors..cctor()
   at Avalonia.Media.KnownColors.ToBrush(Avalonia.Media.KnownColor)
   at Avalonia.Media.Brushes.get_Black()
   at Avalonia.Controls.TextBlock..cctor()
   at Avalonia.Controls.Primitives.TemplatedControl..cctor()
   at Avalonia.Controls.Window..cctor()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime..cctor()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime..ctor()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.String[], Avalonia.Controls.ShutdownMode)
   at GDMENUCardManager.Program.Main(System.String[])
[1]    543118 IOT instruction (core dumped)  ./GDMENUCardManager
```

ICU deps are installed properly, the solution to get around this error was to do this:
`export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`

Then the application ran fine. Putting this here to help folks that may run into this and perhaps help the dev to figure out a better solution.

**Comment by sonik-br** [comment]
Thanks for the heads up.
I can also set this on the app code. I'm going to do some tests and let you know how this goes.
